"""entries table

Revision ID: 1eeda2d3915e
Revises: f604a406f5ea
Create Date: 2020-09-15 10:54:52.291851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeda2d3915e'
down_revision = 'f604a406f5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_license_plate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
