"""entries table

Revision ID: 4ce98fd7cbce
Revises: 
Create Date: 2020-09-15 12:27:39.957294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce98fd7cbce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_vehicle', sa.Integer(), nullable=True),
    sa.Column('fk_period', sa.Integer(), nullable=True),
    sa.Column('initial_hour', sa.String(), nullable=True),
    sa.Column('final_hour', sa.String(), nullable=True),
    sa.Column('hour_quantity', sa.String(), nullable=True),
    sa.Column('total_value', sa.String(), nullable=True),
    sa.Column('order_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('period',
    sa.Column('period_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initial_day', sa.String(), nullable=True),
    sa.Column('final_day', sa.String(), nullable=True),
    sa.Column('initial_hour', sa.String(), nullable=True),
    sa.Column('final_hour', sa.String(), nullable=True),
    sa.Column('value_per_hour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('period_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_license_plate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('products')
    op.drop_table('period')
    op.drop_table('order')
    # ### end Alembic commands ###
