"""entries table

Revision ID: 52b21b3303cc
Revises: 1eeda2d3915e
Create Date: 2020-09-15 11:12:55.572069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b21b3303cc'
down_revision = '1eeda2d3915e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('initial_day', sa.String(), nullable=True),
    sa.Column('final_day', sa.String(), nullable=True),
    sa.Column('initial_hour', sa.Float(), nullable=True),
    sa.Column('final_hour', sa.Float(), nullable=True),
    sa.Column('value_per_hour', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('period_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period')
    # ### end Alembic commands ###
