"""entries table

Revision ID: cc9dbe0f1b47
Revises: 52b21b3303cc
Create Date: 2020-09-15 11:34:38.142937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9dbe0f1b47'
down_revision = '52b21b3303cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle', sa.Integer(), nullable=True),
    sa.Column('fk_period', sa.Integer(), nullable=True),
    sa.Column('initial_hour', sa.String(), nullable=True),
    sa.Column('final_hour', sa.String(), nullable=True),
    sa.Column('hour_quantity', sa.String(), nullable=True),
    sa.Column('total_value', sa.String(), nullable=True),
    sa.Column('order_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
