"""entries table

Revision ID: dbe2b7fae3a3
Revises: 
Create Date: 2020-09-15 15:16:43.545191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe2b7fae3a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle', sa.String(), nullable=True),
    sa.Column('fk_period', sa.String(), nullable=True),
    sa.Column('initial_hour', sa.String(), nullable=True),
    sa.Column('final_hour', sa.String(), nullable=True),
    sa.Column('hour_quantity', sa.String(), nullable=True),
    sa.Column('total_value', sa.String(), nullable=True),
    sa.Column('order_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('period',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('initial_day', sa.String(), nullable=True),
    sa.Column('final_day', sa.String(), nullable=True),
    sa.Column('initial_hour', sa.String(), nullable=True),
    sa.Column('final_hour', sa.String(), nullable=True),
    sa.Column('value_per_hour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('period_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('teste_order',
    sa.Column('teste_order_id', sa.Integer(), nullable=False),
    sa.Column('initial_day', sa.String(), nullable=True),
    sa.Column('final_day', sa.String(), nullable=True),
    sa.Column('initial_hour', sa.String(), nullable=True),
    sa.Column('final_hour', sa.String(), nullable=True),
    sa.Column('value_per_hour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('teste_order_id')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_license_plate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('teste_order')
    op.drop_table('products')
    op.drop_table('period')
    op.drop_table('order')
    # ### end Alembic commands ###
